### ISSUE TITLE
cannot load such file -- net\http

### ISSUE THREAD

**Issue by ghost** [SubPointSolutions/uplift-vagrant#13]
Vagrant 2.2.4 on 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

```
vagrant plugin list
docker (0.4.0, global)
  - Version Constraint: > 0
vagrant-env (0.0.3, global)
  - Version Constraint: > 0
vagrant-hosts (2.9.0, global)
  - Version Constraint: > 0
vagrant-reload (0.0.1, global)
  - Version Constraint: > 0
vagrant-scp (0.5.7, global)
  - Version Constraint: > 0
vagrant-uplift (0.2.1902.49, global)
  - Version Constraint: > 0

 INFO manager: Loading plugin `vagrant-uplift` with default require: `vagrant-uplift`
 INFO manager: Registered plugin: vagrant-uplift-checkpoint
ERROR manager: Failed to load plugin `vagrant-uplift` with default require. - LoadError: cannot load such file -- net\http
 INFO manager: Loading plugin `vagrant-uplift` with slash require: `vagrant/uplift`
ERROR manager: Plugin loading error: LoadError - cannot load such file -- vagrant/uplift
DEBUG manager: /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
DEBUG manager: /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:322:in `rescue in block in load_plugins'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:314:in `block in load_plugins'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:312:in `each'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:312:in `load_plugins'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:176:in `initialize'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
DEBUG manager: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PluginLoadError: The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/uplift>
ERROR vagrant: The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/uplift
ERROR vagrant: /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:342:in `rescue in load_plugins'
/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:310:in `load_plugins'
/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:176:in `initialize'
/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/uplift
```

**Comment by SubPointSupport** [comment]
Hi @brendanstephens , sorry for this experience.

Did you have this problem with early versions of the vagrant-uplift plugin?
* https://rubygems.org/gems/vagrant-uplift

Most likely, the following line introduces a regression. Should be `net/http` instead of `net\http`
https://github.com/SubPointSolutions/uplift-vagrant/blob/fb223761d9cc02a0f486effc34070520c300769f/vagrant-uplift/lib/vagrant-uplift/appinsights.rb#L10

Several options here:
* Downgrade to the early version of the plugin, we did not have AppInsights telemetry and hence no `net\http`
* Manually change this line to  `net/http` in your vagrant plugin folder (somewhere under ~/.vagrant.d\gems\2.4.4\gems\vagrant-uplift )
* We are looking into this, will add more regression testing to ensure that plugin can be loaded on all platforms (such as dry run under several docker containers should help)
